name: Semantic Versioning and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant execute permission to the script
        run: chmod +x calculate_version.sh

      - name: Get last release version
        id: last_release
        run: echo ::set-output name=VERSION::$(git describe --tags --abbrev=0)

      - name: Calculate new version
        id: calc_version
        run: |
          LAST_VERSION=${{ steps.last_release.outputs.VERSION }}
          NEW_VERSION=$(./calculate_version.sh $LAST_VERSION)
          echo ::set-output name=NEW_VERSION::$NEW_VERSION

      - name: Bump version in files
        run: |
          NEW_VERSION=${{ steps.calc_version.outputs.NEW_VERSION }}
          # Update version in your project files (e.g., Unity project)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calc_version.outputs.NEW_VERSION }}
          release_name: Release ${{ steps.calc_version.outputs.NEW_VERSION }}
          body: |
            # Changes since last release:
            $(git log --pretty=format:"%s" ${{ steps.last_release.outputs.VERSION }}..HEAD)
