name: Push Markdown File to Wiki

on:
  workflow_dispatch:

jobs:
  push_to_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Download Markdown File from OneDrive
        run: |
          curl -L -o Requirements.md "https://liveconcordia-my.sharepoint.com/:x:/g/personal/pa_nir_live_concordia_ca/EQImy4AXJwxIqTWoYEDgQPEBBAM-BsF49jZzKyxsWFyljQ?e=nre07e&download=1"

      - name: Push Markdown File to Wiki
        run: |
          git clone https://github.com/Niravanaa/testrepo.wiki.git wiki
          cp Requirements.md wiki/
          cd wiki
          git add Requirements.md
          git commit -m "Add Markdown file to wiki"
          git push
